name: .PR Close

on:
  workflow_call:
    inputs:
      ### Typical / recommended
      cleanup:
        description: "Type of cleanup; e.g. helm or label"
        required: false
        type: string
      environment:
        description: Environment name; omit for PRs
        required: false
        type: string
      packages:
        description: "Space-separated list of packages to promote"
        required: false
        type: string
      remove_pvc:
        required: false
        default: data-${{ github.event.repository.name }}-${{ github.event.number }}-bitnami-pg-0
        type: string
        description: "Comma separated list of PVCs to remove"

      ### Usually a bad idea / not recommended
      merge_branch:
        description: "Merge target branch"
        required: false
        type: string
        default: ${{ github.event.repository.default_branch }}
      cleanup_name:
        description: "Use if template/cleanup name differs from repo; space-separated for multiple names"
        type: string
        default: ""
      organization:
        description: "GitHub organization; e.g. bcgov"
        default: ${{ github.repository_owner }}
        required: false
        type: string
      repository:
        description: "GitHub repository, e.g. quickstart-openshift"
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      tag_promote:
        description: "Tag to promote to; e.g. latest, test, demo or prod"
        default: latest
        required: false
        type: string
      target:
        description: "Target; e.g. PR number, test or prod"
        default: ${{ github.event.number }}
        required: false
        type: string

    secrets:
      oc_namespace:
        description: "OpenShift namespace"
        required: false
      oc_token:
        description: "OpenShift token"
        required: false
      oc_server:
        description: "OpenShift server, defaults to https://api.silver.devops.gov.bc.ca:6443"
        required: false

env:
  DEFAULT_OC_SERVER: https://api.silver.devops.gov.bc.ca:6443

jobs:
  vars:
    if: inputs.packages != ''
    runs-on: ubuntu-24.04
    outputs:
      packages: ${{ steps.packages.outputs.packages }}
    steps:
      - id: packages
        env:
          INPUT_PACKAGES: ${{ inputs.packages }}
        run: |
          # Convert packages to JSON array for job matrix
          read -r -a pkgs <<< "$INPUT_PACKAGES"
          echo "packages=$(jq -cn '$ARGS.positional' --args "${pkgs[@]}")" >> "$GITHUB_OUTPUT"

      - env:
          INPUT_PACKAGES: ${{ inputs.packages }}
          PR_MERGED: ${{ github.event.pull_request.merged }}
          PR_BASE_REF: ${{ github.event.pull_request.base.ref }}
          MERGE_BRANCH: ${{ inputs.merge_branch }}
        run: |
          # Diagnostic vars
          read -r -a pkgs <<< "$INPUT_PACKAGES"
          echo "packages=$(jq -cn '$ARGS.positional' --args "${pkgs[@]}")"
          echo "github.event.pull_request.merged=$PR_MERGED"
          echo "github.event.pull_request.base.ref=$PR_BASE_REF"
          echo "inputs.merge_branch=$MERGE_BRANCH"

  retags:
    name: Retags
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == inputs.merge_branch
    needs: vars
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    strategy:
      matrix:
        package: ${{ fromJson(needs.vars.outputs.packages) }}
    timeout-minutes: 1
    steps:
      - uses: shrink/actions-docker-registry-tag@e6aaef25c595b6e0edd18bf4c7dbfea3abd43299 # v5
        with:
          registry: ghcr.io
          repository: ${{ inputs.organization }}/${{ inputs.repository }}/${{ matrix.package }}
          target: ${{ inputs.target }}
          tags: ${{ inputs.tag_promote }}

  # Clean up OpenShift when PR closed
  cleanup:
    name: OpenShift
    if: (github.event_name == 'pull_request' || github.event_name == 'pull_request_target') && github.event.action == 'closed' && (inputs.cleanup == 'helm' || inputs.cleanup == 'label')
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Helm Cleanup
        env:
          release: ${{ inputs.repository }}-${{ inputs.target }}
        if: inputs.cleanup == 'helm'
        uses: bcgov/action-oc-runner@111868d1fc50db0a40417ba321d865ef5c931bbd # v1.7.0
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          oc_server: ${{ secrets.oc_server || env.DEFAULT_OC_SERVER }}
          commands: |
            # Cleanup for Helm deployments
            if helm status "$release" >/dev/null 2>&1; then
              helm uninstall --no-hooks "$release"
            else
              echo "Not found: $release"
            fi

      - name: OC Template (label) Cleanup
        if: inputs.cleanup == 'label'
        uses: bcgov/action-oc-runner@111868d1fc50db0a40417ba321d865ef5c931bbd # v1.7.0
        env:
          CLEANUP_NAME: ${{ inputs.cleanup_name }}
          REPOSITORY: ${{ inputs.repository }}
          TARGET: ${{ inputs.target }}
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          oc_server: ${{ secrets.oc_server || env.DEFAULT_OC_SERVER }}
          commands: |
            set -x
            # Cleanup for OpenShift template deployments, uses labels

            # Remove old build runs, build pods and deployment pods
            if [ -n "$CLEANUP_NAME" ]; then
              for name in $CLEANUP_NAME; do
                oc delete all,cm,pvc,secret,networkpolicy,routes,hpa -l "app=${name}" || \
                  echo "Not found: ${name}"
              done
            else
              target_app="${REPOSITORY}-${TARGET}"
              oc delete all,cm,pvc,secret,networkpolicy,routes,hpa -l "app=${target_app}" || \
                echo "Not found: ${target_app}"
            fi

      - name: Remove PVCs
        if: inputs.remove_pvc != ''
        uses: bcgov/action-oc-runner@111868d1fc50db0a40417ba321d865ef5c931bbd # v1.7.0
        env:
          REMOVE_PVC: ${{ inputs.remove_pvc }}
        with:
          oc_namespace: ${{ secrets.oc_namespace }}
          oc_token: ${{ secrets.oc_token }}
          oc_server: ${{ secrets.oc_server || env.DEFAULT_OC_SERVER }}
          commands: |
            # Remove PVCs from OpenShift when PR closed
            for pvc in $(echo "$REMOVE_PVC" | tr ',' ' '); do
              oc delete pvc "$pvc" || echo "Not found: $pvc"
            done
